-- init database
DROP DATABASE IF EXISTS User;

CREATE DATABASE User;

USE User;

CREATE TABLE IF NOT EXISTS UserInfo(
    id INT UNSIGNED  AUTO_INCREMENT PRIMARY KEY ,
    username VARCHAR(32) NOT  NULL ,
    password VARCHAR(96) NOT NULL ,
    salt VARCHAR(96) NOT NULL 
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;